namespace Ruumly.Backend.DTOs.Responses;

public record OrderDto(
    Guid              Id,
    Guid              BookingId,
    Guid              SupplierId,
    string            SupplierName,
    string            ListingTitle,
    string            ListingType,
    string            IntegrationType,
    string            CustomerName,
    string            CustomerEmail,
    string            CustomerPhone,
    string            City,
    string            StartDate,
    string?           EndDate,
    string            Duration,
    List<string>      Extras,
    decimal           BasePrice,
    decimal           PlatformPrice,
    decimal           SupplierPrice,
    decimal           ExtrasTotal,
    decimal           Total,
    decimal           Margin,
    string            Status,
    string?           ApprovedBy,
    string?           ApprovedAt,
    string?           PostingChannel,
    string?           SentAt,
    string?           ConfirmedAt,
    string            Notes,
    string            CreatedAt,
    List<FulfillmentEventDto> FulfillmentEvents
);
