namespace Ruumly.Backend.DTOs.Responses;

public record SupplierDto(
    Guid    Id,
    string  Name,
    string  RegistryCode,
    string  ContactName,
    string  ContactEmail,
    string  ContactPhone,
    string  IntegrationType,
    string? ApiEndpoint,
    string? ApiAuthType,
    string? ApiAuthToken,
    string? RecipientEmail,
    bool    IsActive,
    string  IntegrationHealth,
    decimal PartnerDiscountRate,
    decimal ClientDiscountRate,
    string? Notes,
    string? Iban,
    string? BankAccountName,
    string? BankName,
    string  CreatedAt,
    string  UpdatedAt,
    int     OrdersTotal,
    decimal Revenue,
    IntegrationSettingsDto? IntegrationSettings,
    string    BillingModel,
    string    Tier,
    decimal   CommissionRate,
    decimal   MonthlyFee,
    bool      HasFullAnalytics,
    bool      CanHavePromotedBadge,
    bool      FoundingPartner,
    DateTime? OnboardingStartedAt,
    bool      IsInOnboarding,
    int       OnboardingDaysRemaining,
    bool      IsVerified,
    string    PriorityLevel,
    string?   Country,
    // Partner page fields
    string?   Slug,
    bool      IsPartnerPagePublished,
    string?   Tagline,
    string?   LongDescriptionEt,
    string?   LongDescriptionEn,
    string?   LongDescriptionRu,
    string?   LogoUrl,
    string?   HeroImageUrl,
    string?   WebsiteUrl,
    int?      FoundedYear,
    string?   GooglePlaceId,
    string?   PartnerPageUrl   // null when no slug, else "/partner/{slug}"
);
